name: Merge and Squash

on: 
  pull_request:
    branches:
      - 'device-*'
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git 
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0  # full history for merging
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote add upstream https://github.com/${{ github.repository }}.git
        git fetch upstream main

    - name: Try Fast-Forward Merge
      id: merge_attempt
      run: |
        git checkout main
        git merge --ff-only ${{ github.head_ref }} || echo "conflict" > merge_failed

    - name: Check for Conflict
      id: check_conflict
      run: |
        if [ -f merge_failed ]; then
          echo "conflict=true" >> $GITHUB_OUTPUT
        else
          echo "conflict=false" >> $GITHUB_OUTPUT
        fi

    - name: Push merged main if no conflict
      if: steps.check_conflict.outputs.conflict == 'false'
      run: |
        git push origin main

    - name: Notify Slack if conflict
      if: steps.check_conflict.outputs.conflict == 'true'
      uses: slackapi/slack-github-action@v1.25.0
      with:
        payload: |
          {
            "text": ":warning: *Merge conflict detected!*",
            "attachments": [
              {
                "text": "PR #${{ github.event.pull_request.number }} has conflicts with `main`. Please resolve manually."
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


